rtabmap:
  ros__parameters:
    Rtabmap/StartMapOnLoopClosure: true
    Odom/Strategy: 1
    Odom/FeatureType: 6
    Odom/MinInliers: 15
    Odom/ResetCountdown: 1
    GFTT/MinDistance: 7
    RGBD/ProximityBySpace: true
    RGBD/ProximityPathMaxNeighbors: 10
    RGBD/LoopClosureReextractFeatures: true
    Vis/MinInliers: 15
    Grid/RangeMax: 4.0
    Reg/Strategy: 2
    ICP/PointToPlane: true
    ICP/Iterations: 25
    ICP/MaxCorrespondenceDistance: 0.08
